version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: 'kewin'
      POSTGRES_PASSWORD: 'kewin'
      POSTGRES_DB: 'tempRecords'
    ports:
      - "5432:5432"